// <auto-generated />
using System;
using DigitalWareBackEnd.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalWareBackEnd.Migrations
{
    [DbContext(typeof(DigitalWareContext))]
    [Migration("20220529151112_migracionInicial")]
    partial class migracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DigitalWareBackEnd.Models.DetFacturaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("cantidadProducto")
                        .HasColumnType("int");

                    b.Property<int>("idFactura")
                        .HasColumnType("int");

                    b.Property<int>("idProducto")
                        .HasColumnType("int");

                    b.Property<int>("totalFactura")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idFactura");

                    b.HasIndex("idProducto");

                    b.ToTable("detFactura");
                });

            modelBuilder.Entity("DigitalWareBackEnd.Models.FacturaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("dniPersona")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("valorPagado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("dniPersona");

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("DigitalWareBackEnd.Models.PersonaModel", b =>
                {
                    b.Property<int>("dni")
                        .HasColumnType("int");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("dni");

                    b.ToTable("personas");
                });

            modelBuilder.Entity("DigitalWareBackEnd.Models.ProductoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("existencia")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("precioVenta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("DigitalWareBackEnd.Models.DetFacturaModel", b =>
                {
                    b.HasOne("DigitalWareBackEnd.Models.FacturaModel", "FacturaModel")
                        .WithMany()
                        .HasForeignKey("idFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalWareBackEnd.Models.ProductoModel", "ProductoModel")
                        .WithMany()
                        .HasForeignKey("idProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacturaModel");

                    b.Navigation("ProductoModel");
                });

            modelBuilder.Entity("DigitalWareBackEnd.Models.FacturaModel", b =>
                {
                    b.HasOne("DigitalWareBackEnd.Models.PersonaModel", "PersonaModel")
                        .WithMany()
                        .HasForeignKey("dniPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonaModel");
                });
#pragma warning restore 612, 618
        }
    }
}
